import Vue from "vue"
import {
  Tabbar,
  TabbarItem,
  Search,
  Icon,
  Sku,
  NavBar,
  Swipe,
  SwipeItem,
  Lazyload,
  GoodsAction,
  GoodsActionIcon,
  GoodsActionButton,
  Form,
  Field,
  Button,
  NumberKeyboard,
  Popup,
  Checkbox,
  CheckboxGroup,
  Card,
  SubmitBar,
  Tag,
  ContactCard,
  AddressEdit,
  Collapse,
  CollapseItem,
  Cell,
  CellGroup,
  RadioGroup,
  Radio,
  Overlay,
  Area,
  SwipeCell
} from "vant"
Vue.use(Tabbar)
  .use(TabbarItem)
  .use(Search)
  .use(Icon)
  .use(Sku)
  .use(NavBar)
  .use(Swipe)
  .use(SwipeItem)
  .use(Lazyload)
  .use(GoodsAction)
  .use(GoodsActionIcon)
  .use(GoodsActionButton)
  .use(Form)
  .use(Field)
  .use(Button)
  .use(NumberKeyboard)
  .use(Popup)
  .use(Checkbox)
  .use(CheckboxGroup)
  .use(Card)
  .use(SubmitBar)
  .use(Tag)
  .use(ContactCard)
  .use(AddressEdit)
  .use(Collapse)
  .use(CollapseItem)
  .use(Cell)
  .use(CellGroup)
  .use(RadioGroup)
  .use(Radio)
  .use(Overlay)
  .use(Area)
  .use(SwipeCell)

